<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="HDC-ITADM3152" name="reverseSentenceTest.TestReverseSentence" tests="6" failures="0" timestamp="23 Dec 2019 05:34:04 GMT" time="0.073" errors="1">
  <testcase name="TC06ValidatePalindromes" time="0.001" classname="reverseSentenceTest.TestReverseSentence">
    <error type="java.lang.AssertionError" message="String revarsal failed; palindrome test 4 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: String revarsal failed; palindrome test 4 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at reverseSentenceTest.TestReverseSentence.TC06ValidatePalindromes(TestReverseSentence.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- TC06ValidatePalindromes -->
  <testcase name="TC03ValidateOnlySpecialCharacters" time="0.001" classname="reverseSentenceTest.TestReverseSentence"/>
  <testcase name="TC04ValidateDigits" time="0.001" classname="reverseSentenceTest.TestReverseSentence"/>
  <testcase name="TC01ValidateReversingValidSentence" time="0.053" classname="reverseSentenceTest.TestReverseSentence"/>
  <testcase name="TC02ValidateEmptySentences" time="0.016" classname="reverseSentenceTest.TestReverseSentence"/>
  <testcase name="TC05ValidateCombination" time="0.001" classname="reverseSentenceTest.TestReverseSentence"/>
</testsuite> <!-- reverseSentenceTest.TestReverseSentence -->
